server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sentinelcore
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: 1234567890123456789012345678901234567890123456789012345678901234
    expiration: 300000
    refreshExpiration: 604800000

#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/sentinel_logs